languageCode: "en"
title: "The Context Podcast"

baseUrl: "http://thecontext.github.com/website"
permalinks:
  post: ":slug"

params:
  description: "The Context is a podcast about Android development and everything related."

menu:
  left:
    - name: "Episodes"
      url: "/"
  right:
    - name: "Pocket Casts"
      url: "https://pca.st/hYck"
      weight: 3
    - name: "iTunes"
      url: "https://itunes.apple.com/us/podcast/the-context-androiddev/id1081726814"
      weight: 2
    - name: "RSS"
      url: "https://raw.githubusercontent.com/artem-zinnatullin/TheContext-Podcast/master/feed.rss"
      weight: 1

theme: "context"

googleAnalytics: "UA-126647247-1"

enableEmoji: true

disableKinds:
  - section
  - taxonomy
  - taxonomyTerm
  - rss
